server:
  port: 8080

spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

zuul:
  ignoredServices: "*"
  routes:
    user:
      path: /user/**
      stripPrefix: false
    payment:
      path: /payment/**
      stripPrefix: false
    core:
      path: /core/**
      stripPrefix: false

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
  threadpool:
    default:
      coreSize: 20 # 并发执行的最大线程数，默认10
      maxQueueSize: 3000 # BlockingQueue的最大队列数